server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#  cloud:
#    config:
#      server:
#        git:
#          # uri: file:///Users/dream/Documents/lab/tutorial/git-local-repo
#          uri: https://github.com/link-mozy/spring-cloud-config
#          # username: [your username]
#          # password: [your password]
#          default-label: main
  # Native File Repository
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Documents/lab/tutorial/native-file-repo
        git:
          uri: https://github.com/link-mozy/spring-cloud-config

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh